from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path

import yfinance
from axe_core import Tracer
from axe_core.llm import chat_json
from axe_core.paths import public_dir
from axe_fundamental.reports import update_report_index
from jinja2 import Template


SYSTEM_PROMPT = """You are Axe Capital's Fundamental Analyst. Analyze company fundamentals: business quality, earnings, balance sheet, valuation. Return JSON with: summary, key_findings, data_sources, confidence, report."""


MD_TEMPLATE = """# Fundamental Analysis: {{ ticker }}

**Date:** {{ generated_at }}
**Analyst:** Fundamental Agent
**Confidence:** {{ confidence }}/10

---

## Executive Summary

{{ summary }}

---

## Key Findings

{% for finding in key_findings %}
- {{ finding }}
{% endfor %}

## Detailed Report

{{ report }}

## Data Sources

{% for source in data_sources %}
- {{ source }}
{% endfor %}

---
*Report generated by Axe Capital Fundamental Analyst*
"""


def run_fundamental_analysis(ticker: str, api_key: str, force: bool = False) -> dict:
    tracer = Tracer(agent="axe_fundamental")
    tracer.start()
    
    pub = public_dir()
    reports_dir = pub / "analyst-reports"
    reports_dir.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")
    json_path = reports_dir / f"{ticker}-fundamental-{timestamp}.json"
    md_path = reports_dir / f"{ticker}-fundamental-{timestamp}.md"
    
    if json_path.exists() and not force:
        tracer.finalize(status="skipped", summary=f"Report exists: {json_path.name}")
        return {"json_path": json_path, "md_path": md_path, "skipped": True}
    
    tracer.event(step="fetch_data", thought=f"Fetching data for {ticker}")
    try:
        stock = yfinance.Ticker(ticker)
        info = stock.info
    except Exception as e:
        tracer.finalize(status="failed", summary=f"Failed: {e}")
        raise RuntimeError(f"Failed: {e}")
    
    context = {"ticker": ticker, "company_name": info.get("shortName", "Unknown"), "sector": info.get("sector", "Unknown"), "market_cap": info.get("marketCap", "N/A"), "pe_ratio": info.get("trailingPE", "N/A"), "eps": info.get("trailingEps", "N/A"), "revenue": info.get("totalRevenue", "N/A"), "gross_margin": info.get("grossMargins", "N/A"), "operating_margin": info.get("operatingMargins", "N/A")}
    
    tracer.event(step="llm_analysis", thought="Running LLM analysis")
    result = chat_json(api_key=api_key, model="gpt-4o-mini", system=SYSTEM_PROMPT, user=context, max_tokens=1500, temperature=0.3)
    
    result["generated_at"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    result["ticker"] = ticker
    result["agent"] = "fundamental"
    result["data_sources"] = ["yfinance"]
    
    json_path.write_text(json.dumps(result, indent=2))
    
    template = Template(MD_TEMPLATE)
    md_content = template.render(ticker=ticker, generated_at=result.get("generated_at", ""), confidence=result.get("confidence", 5), summary=result.get("summary", "N/A"), key_findings=result.get("key_findings", []), report=result.get("report", "N/A"), data_sources=result.get("data_sources", []))
    md_path.write_text(md_content)
    update_report_index(reports_dir, ticker, "fundamental", json_path, md_path)
    
    tracer.finalize(status="success", summary=f"Complete for {ticker}", artifact_written=str(json_path.name))
    
    return {"json_path": json_path, "md_path": md_path, "skipped": False}
